"""adjust field name to is_default_group group membership

Revision ID: 05f117601125
Revises: ee14f41efecf
Create Date: 2025-02-16 21:10:46.633788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f117601125'
down_revision: Union[str, None] = 'ee14f41efecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_membership', sa.Column('is_default_group', sa.Boolean(), nullable=False))
    op.drop_column('group_membership', 'default_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_membership', sa.Column('default_group', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('group_membership', 'is_default_group')
    # ### end Alembic commands ###
