"""add unique constraint to category title

Revision ID: 0ef2e0d84738
Revises: 952f24ca2654
Create Date: 2025-01-19 16:52:25.332865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef2e0d84738'
down_revision: Union[str, None] = '952f24ca2654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_challenge_category_title', table_name='challenge_category')
    op.create_index(op.f('ix_challenge_category_title'), 'challenge_category', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_category_title'), table_name='challenge_category')
    op.create_index('ix_challenge_category_title', 'challenge_category', ['title'], unique=False)
    # ### end Alembic commands ###
