"""add year to challenge table

Revision ID: 1c9d4c910046
Revises: a87ac4094dab
Create Date: 2025-02-22 22:41:45.960494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9d4c910046'
down_revision: Union[str, None] = 'a87ac4094dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge', 'year')
    # ### end Alembic commands ###
