"""addd is_admin_request to Allowed Email Address

Revision ID: 26cd378747a3
Revises: 05f117601125
Create Date: 2025-02-16 21:28:54.663038

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26cd378747a3"
down_revision: Union[str, None] = "05f117601125"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("allowed_email_address", sa.Column("is_admin_request", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("allowed_email_address", "is_admin_request")
    # ### end Alembic commands ###
