"""change admin request track keeping

Revision ID: 282d3b5fe1d1
Revises: 6aa906bcf27e
Create Date: 2025-02-16 21:52:29.750410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282d3b5fe1d1'
down_revision: Union[str, None] = '6aa906bcf27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowed_email_address', sa.Column('is_admin_request_for_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'allowed_email_address', 'group', ['is_admin_request_for_group_id'], ['id'])
    op.drop_column('allowed_email_address', 'is_admin_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowed_email_address', sa.Column('is_admin_request', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'allowed_email_address', type_='foreignkey')
    op.drop_column('allowed_email_address', 'is_admin_request_for_group_id')
    # ### end Alembic commands ###
