"""remove unique constraint for email in allowed email

Revision ID: 2f33a73d5d18
Revises: 1c9d4c910046
Create Date: 2025-03-01 22:28:52.982269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f33a73d5d18'
down_revision: Union[str, None] = '1c9d4c910046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('allowed_email_address_email_key', 'allowed_email_address', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('allowed_email_address_email_key', 'allowed_email_address', ['email'])
    # ### end Alembic commands ###
