"""add isbn, remove unique conatraint book name

Revision ID: 514174b2e149
Revises: 
Create Date: 2025-02-02 09:19:49.481636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514174b2e149'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_table', sa.Column('isbn', sa.String(), nullable=True))
    op.drop_constraint('association_table_book_name_key', 'association_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('association_table_book_name_key', 'association_table', ['book_name'])
    op.drop_column('association_table', 'isbn')
    # ### end Alembic commands ###
