"""add created_at to group

Revision ID: 53171fb5046a
Revises: 8bd16c607087
Create Date: 2025-02-16 20:46:19.059057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53171fb5046a'
down_revision: Union[str, None] = '8bd16c607087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'created_at')
    # ### end Alembic commands ###
