"""add admin id to group

Revision ID: 58be1f32c3c0
Revises: 53171fb5046a
Create Date: 2025-02-16 20:47:59.979393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58be1f32c3c0'
down_revision: Union[str, None] = '53171fb5046a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'group', 'user', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'admin_id')
    # ### end Alembic commands ###
