"""use timestamp for joined_at in group membership

Revision ID: 7f8e3ea3d5c6
Revises: 58be1f32c3c0
Create Date: 2025-02-16 21:05:44.510749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8e3ea3d5c6'
down_revision: Union[str, None] = '58be1f32c3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_membership', 'joined_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_membership', sa.Column('joined_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
