"""add isbn temporarily back

Revision ID: 8bd16c607087
Revises: a5de8ae39c6c
Create Date: 2025-02-16 19:44:10.394060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd16c607087'
down_revision: Union[str, None] = 'a5de8ae39c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_table', sa.Column('isbn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('association_table', 'isbn')
    # ### end Alembic commands ###
