"""add trophy table

Revision ID: 8bf99bd7929d
Revises: 514174b2e149
Create Date: 2025-02-03 21:58:04.316943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf99bd7929d'
down_revision: Union[str, None] = '514174b2e149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trophy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('MONTHLY', 'YEARLY', name='trophytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trophy')
    # ### end Alembic commands ###
