"""add group fields

Revision ID: a5de8ae39c6c
Revises: 2bb3e78a6cce
Create Date: 2025-02-16 19:39:30.869254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5de8ae39c6c'
down_revision: Union[str, None] = '2bb3e78a6cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_table', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'association_table', 'group', ['group_id'], ['id'])
    op.drop_column('association_table', 'isbn')
    op.add_column('challenge', sa.Column('description', sa.String(), nullable=False))
    op.add_column('challenge_category', sa.Column('challenge_id', sa.Integer(), nullable=True))
    op.add_column('challenge_category', sa.Column('group_id_custom_category', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_challenge_category_challenge_id'), 'challenge_category', ['challenge_id'], unique=False)
    op.create_foreign_key(None, 'challenge_category', 'challenge', ['challenge_id'], ['id'])
    op.create_foreign_key(None, 'challenge_category', 'group', ['group_id_custom_category'], ['id'])
    op.add_column('group', sa.Column('challenge_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'challenge', ['challenge_id'], ['id'])
    op.add_column('group_membership', sa.Column('default_group', sa.Boolean(), nullable=False))
    op.add_column('trophy', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trophy', 'group', ['group_id'], ['id'])
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    op.drop_constraint(None, 'trophy', type_='foreignkey')
    op.drop_column('trophy', 'group_id')
    op.drop_column('group_membership', 'default_group')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'challenge_id')
    op.drop_constraint(None, 'challenge_category', type_='foreignkey')
    op.drop_constraint(None, 'challenge_category', type_='foreignkey')
    op.drop_index(op.f('ix_challenge_category_challenge_id'), table_name='challenge_category')
    op.drop_column('challenge_category', 'group_id_custom_category')
    op.drop_column('challenge_category', 'challenge_id')
    op.drop_column('challenge', 'description')
    op.add_column('association_table', sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.drop_column('association_table', 'group_id')
    # ### end Alembic commands ###
