"""drop title unique constraint and add is_user_request_for_group_id

Revision ID: a87ac4094dab
Revises: ed27ff39db63
Create Date: 2025-02-22 21:21:27.445596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87ac4094dab'
down_revision: Union[str, None] = 'ed27ff39db63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowed_email_address', sa.Column('is_user_request_for_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'allowed_email_address', 'group', ['is_user_request_for_group_id'], ['id'])
    op.drop_index('ix_challenge_category_title', table_name='challenge_category')
    op.create_index(op.f('ix_challenge_category_title'), 'challenge_category', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_category_title'), table_name='challenge_category')
    op.create_index('ix_challenge_category_title', 'challenge_category', ['title'], unique=True)
    op.drop_constraint(None, 'allowed_email_address', type_='foreignkey')
    op.drop_column('allowed_email_address', 'is_user_request_for_group_id')
    # ### end Alembic commands ###
