"""add year to trophy table nullable True

Revision ID: c7afaf41f05d
Revises: 204238475e74
Create Date: 2025-02-09 13:53:10.067473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7afaf41f05d'
down_revision: Union[str, None] = '204238475e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trophy', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trophy', 'year')
    # ### end Alembic commands ###
