"""add month to trophy table

Revision ID: d9118dafb6ad
Revises: 8bf99bd7929d
Create Date: 2025-02-07 21:52:56.919979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9118dafb6ad'
down_revision: Union[str, None] = '8bf99bd7929d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trophy', sa.Column('month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trophy', 'month')
    # ### end Alembic commands ###
